name: CDK Workshop
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with: 
          python-version: '3.9'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install aws-cdk-lib

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
         aws-region: "eu-north-1"
    
    - name: CDK Synth
    run: cdk synth  

